[tool.poetry]
name = "homework_03"
version = "0.1.0"
description = ""
authors = ["temirs <temir.salavatov@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.17.1"
fastapi = "^0.73.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
